In [31]:
import pandas as pd
import sqlite3
import numpy as np
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import pycountry

ModuleNotFoundError: No module named 'pycountry'

In [7]:
conn = sqlite3.connect("result/nationbuilder.db")

In [8]:
df = pd.read_sql("select * from people", conn)

In [18]:
for col in df.columns:
    if (df[col].values == None).sum() >= 22900:
        df.drop(col, axis=1, inplace=True)

In [25]:
df['created_at'] = pd.to_datetime(df['created_at'])
df['updated_at'] = pd.to_datetime(df['updated_at'])
df.drop('profile_image_url_ssl', axis=1, inplace=True)
df['addr_lat'] = pd.to_numeric(df['addr_lat'])
df['addr_lng'] = pd.to_numeric(df['addr_lng'])

In [30]:
df.loc[~df['addr_lat'].isna()]

,created_at,do_not_call,do_not_contact,email,email_opt_in,employer,first_name,has_facebook,id,is_twitter_follower,...,addr_lat,addr_lng,addr_street_number,addr_street_prefix,addr_street_name,addr_street_type,addr_street_suffix,addr_unit_number,addr_zip4,addr_zip5
2,2023-02-22 12:47:07+00:00,0,0,thekevin.afachao@gmail.com,1,None,Kevin,0,35179,0,...,-30.559482,22.937506,None,None,None,None,None,None,None,None
3,2023-02-22 07:27:31+00:00,0,0,mertatagun@hotmail.com,1,None,Mert,0,35178,0,...,40.203309,29.075547,None,None,None,None,None,None,None,16240
4,2023-02-21 05:22:34+00:00,0,0,mychimulala@gmail.com,1,None,Maneno,0,35177,0,...,-15.881777,34.967198,None,None,None,None,None,None,None,Malawi
5,2023-02-21 02:02:44+00:00,0,0,asaahdericktalah@gmail.com,1,None,Asaah,0,35176,0,...,4.394673,18.558190,None,None,None,None,None,None,None,07498
6,2023-02-19 17:23:58+00:00,0,0,zitaadongo515@gmail.com,1,None,Zita,0,35175,0,...,5.603717,-0.186964,None,None,None,None,None,None,None,233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22895,2019-10-17 09:15:44+00:00,0,0,achillecs@hotmail.com,1,None,Achille,0,1889,0,...,48.856614,2.352222,None,None,None,None,None,None,None,None
22896,2019-10-17 09:15:42+00:00,0,0,pierre.delarochefoucauld@gmail.com,1,None,Pierre,0,1678,0,...,51.507351,-0.127758,None,None,None,None,None,None,None,None
22897,2019-10-17 09:15:42+00:00,0,0,alberto.segolin@yahoo.com,1,None,Alberto,0,1625,0,...,41.871940,12.567380,None,None,None,None,None,None,None,None
22898,2019-10-17 09:15:33+00:00,0,0,mlh95@hotmail.fr,1,None,Marie-Laure,0,1507,0,...,51.507351,-0.127758,None,None,None,None,None,None,None,None
22899,2019-10-17 09:15:32+00:00,0,0,antonio.belloni@sullenote.it,1,None,antonio,0,1377,0,...,41.871940,12.567380,None,None,None,None,None,None,None,None